server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /users {
        proxy_pass http://backend-service:5000/users;
    }

    location /status {
        proxy_pass http://backend-service:5000/status;
    }
}