version: 0.2

phases:

  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 082319703213.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t backend-app ./backend
      - docker build -t frontend-app ./frontend

      - docker tag backend-app:latest 082319703213.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
      - docker tag frontend-app:latest 082319703213.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest

  post_build:
    commands:
      - docker push 082319703213.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
      - docker push 082319703213.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest
      - aws eks update-kubeconfig --region us-east-1 --name AC_EKS_cluster
      - kubectl rollout restart deployment backend-deployment
      - kubectl rollout restart deployment frontend-deployment