apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

        - name: backend

          image: 082319703213.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 5000