apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:
      containers:

      - name: frontend

        image: 082319703213.dkr.ecr.us-east-1.amazonaws.com/frontend-app

        imagePullPolicy: Never

        ports:
        - containerPort: 80